<a href="https://colab.research.google.com/github/fatidevt/data-skills-journey/blob/main/pandas/exercices/filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pandas Tutorial Exercices For Part 4 :

Filtering - Using Conditionals to Filter Rows and Columns

**Beginner Exercises**

In [ ]:
import pandas as pd

data = {
    'name': ['Yasmine', 'Omar', 'Sara', 'Khalid', 'Imane', 'Hamza', 'Ami'],
    'age': [23, 35, 29, 41, 22, 38, 27],
    'city': ['Rab at', 'Casablanca', 'Rabat', 'Fes', 'Marrakech', 'Casablanca', 'Rabat'],
    'salary': [4500, 8200, 6100, 9500, 3800, 7200, 5300],
    'years_experience': [1, 8, 4, 15, 0.5, 10, 3]
}
df = pd.DataFrame(data)

In [ ]:
df

      name  age        city  salary  years_experience
0  Yasmine   23      Rab at    4500               1.0
1     Omar   35  Casablanca    8200               8.0
2     Sara   29       Rabat    6100               4.0
3   Khalid   41         Fes    9500              15.0
4    Imane   22   Marrakech    3800               0.5
5    Hamza   38  Casablanca    7200              10.0
6      Ami   27       Rabat    5300               3.0

Filter people older than 30.

In [ ]:
df

In [ ]:
older_30 = (df['age'] > 30)
df[older_30]

Filter people who live in 'Rabat'.

In [ ]:
rabat_filt = (df['city'] == 'Rabat')
df[rabat_filt]

Filter people with salary >= 6000 AND years_experience > 2.

In [ ]:
salary_filt = (df['salary'] >= 6000) & (df['years_experience'] > 2)
df[salary_filt]

Filter people who live in either 'Fes' or 'Marrakech' (use isin).

In [ ]:
cities = ['Fes' , 'Marrakech']
cities_filt = df['city'].isin(cities)
df[cities_filt]

Filter people who do NOT live in 'Casablanca'.

In [ ]:
#Methode 1
#df[df['city'] != 'Casablanca']
#Methode 2
is_casa = df['city'] == 'Casablanca'
df[~is_casa]

**Intermediate Exercises**

Get the name and salary of everyone earning more than 7000. Don't return the whole dataframe — only those two columns.

In [ ]:
df.head(3)

In [ ]:
salary_filt2 = (df['salary'] > 7000)
df.loc[salary_filt2, ['name' , 'salary']]

Filter people whose name contains the letter 'a' (case-insensitive). This introduces .str methods, which you'll use constantly for messy text data (emails, product names, free-text client fields, etc.).

In [ ]:
# This searches for 'a' OR 'A' — ignores case on BOTH sides
name_filt = df['name'].str.contains('a', case=False)
df[name_filt]

A client emails you: "Send me everyone based in Rabat or Fes, who has more than 3 years of experience, but I only need their name and city — not their salary, that's confidential."

In [ ]:
cities = ['Rabat','Fes']
client_filt = ( df['city'].isin(cities) ) & ( df['years_experience'] > 3 )
df[client_filt]

df.loc[client_filt, ['name' , 'city'] ]

Challenge Problem — "The Messy Client Spreadsheet"

In [ ]:
import pandas as pd
import numpy as np

client_data = {
    'name': ['Yasmine ', 'omar', 'SARA', 'Khalid', 'imane', 'Hamza', 'Lina', 'Youssef'],
    'age': [23, 35, 29, 41, 22, 38, 27, np.nan],
    'city': ['Rabat', 'casablanca', 'Rabat ', 'Fes', 'Marrakech', 'CASABLANCA', np.nan, 'Rabat'],
    'salary': [4500, 8200, 6100, 9500, 3800, 7200, 5300, 6800],
    'years_experience': [1, 8, 4, 15, 0.5, 10, 3, 6],
    'status': ['active', 'active', 'inactive', 'active', 'active', 'inactive', 'active', 'active']
}
client_df = pd.DataFrame(client_data)

Client's request:


"I need a list of all active employees based in Casablanca or Rabat, who have more than 2 years of experience. Give me their name and salary only. Also — some of my data has messy spacing/capitalization, please make sure that doesn't break your filter."

Your task:


1. Clean the city column so 'casablanca', 'CASABLANCA', 'Rabat ' etc. are all treated consistently (hint: .str.strip() and .str.lower() or .str.title(), chained).

2. Build the filter satisfying all the client's conditions (status, city, experience).

3. Return only name and salary for the matching rows.

***Bonus***: handle the NaN in city gracefully — don't let it crash your filter or accidentally get included/excluded wrongly.

In [ ]:
client_df

       name   age        city  salary  years_experience    status
0  Yasmine   23.0       Rabat    4500               1.0    active
1      omar  35.0  casablanca    8200               8.0    active
2      SARA  29.0      Rabat     6100               4.0  inactive
3    Khalid  41.0         Fes    9500              15.0    active
4     imane  22.0   Marrakech    3800               0.5    active
5     Hamza  38.0  CASABLANCA    7200              10.0  inactive
6      Lina  27.0         NaN    5300               3.0    active
7   Youssef   NaN       Rabat    6800               6.0    active

In [ ]:
cities = ['Casablanca', 'Rabat']
city_filt = client_df['city'].str.strip().str.lower().str.title().isin(cities)
exp_filt = client_df['years_experience'] > 2
active_filt = client_df['status'] == 'active'
goal_filt = city_filt & exp_filt & active_filt
client_df.loc[goal_filt , ['name' , 'salary']]

      name  salary
1     omar    8200
7  Youssef    6800