<a href="https://colab.research.google.com/github/fatidevt/data-skills-journey/blob/main/pandas/exercices/read_write.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Tutorial Exercices For Part 11 :
Reading/Writing Data to Different Sources - Excel, JSON, SQL, Etc

df = pd.read_csv('file.csv')

df = pd.read_csv('file.csv', index_col=0)  # if first column is index

df.to_csv('output.csv', index=False)  # index=False — don't save row numbers

df = pd.read_excel('file.xlsx', sheet_name='Sales')  # by name

df = pd.read_excel('file.xlsx', sheet_name=0)        # by index

df.to_excel('output.xlsx', sheet_name='Report', index=False)

In [ ]:
import pandas as pd

data = {
    'name': ['Yasmine', 'Omar', 'Sara', 'Khalid', 'Imane'],
    'department': ['Nursing', 'Admin', 'Pharmacy', 'Nursing', 'Admin'],
    'salary': [6000, 4500, 7200, 6000, 4500],
    'experience': [8, 2, 5, 1, 6]
}
df = pd.DataFrame(data)
df

      name department  salary  experience
0  Yasmine    Nursing    6000           8
1     Omar      Admin    4500           2
2     Sara   Pharmacy    7200           5
3   Khalid    Nursing    6000           1
4    Imane      Admin    4500           6

Save as employees.csv without index

In [ ]:
df.to_csv('employees.csv', index=False)

Read employees.csv → df_csv, print shape

In [ ]:
df_csv = pd.read_csv('employees.csv')
df_csv

      name department  salary  experience
0  Yasmine    Nursing    6000           8
1     Omar      Admin    4500           2
2     Sara   Pharmacy    7200           5
3   Khalid    Nursing    6000           1
4    Imane      Admin    4500           6

Save as employees.xlsx on sheet 'Staff' without index

In [ ]:
df.to_excel('employees.xlsx', sheet_name='Staff', index=False)

Read employees.xlsx from sheet 'Staff' → df_excel

In [ ]:
df_excel = pd.read_excel('employees.xlsx', sheet_name='Staff')
df

      name department  salary  experience
0  Yasmine    Nursing    6000           8
1     Omar      Admin    4500           2
2     Sara   Pharmacy    7200           5
3   Khalid    Nursing    6000           1
4    Imane      Admin    4500           6

Filter Nursing only → save as nursing_only.csv

In [ ]:
filt = df['department'] == 'Nursing'
df[filt].to_csv('nursing_only.csv')

Intermediate ex

In [ ]:
import pandas as pd
import sqlite3

data = {
    'name': ['Yasmine', 'Omar', 'Sara', 'Khalid', 'Imane', 'Hamza', 'Lina'],
    'department': ['Nursing', 'Admin', 'Pharmacy', 'Nursing', 'Admin', 'Pharmacy', 'Nursing'],
    'salary': [6000, 4500, 7200, 6000, 4500, 7200, 6000],
    'city': ['Rabat', 'Casablanca', 'Rabat', 'Fes', 'Casablanca', 'Rabat', 'Fes'],
    'experience': [8, 2, 5, 1, 6, 9, 3]
}
df2 = pd.DataFrame(data)

1. Save df as employees.json, read it back into df_json, verify shape matches.

In [ ]:
df2.to_json('employees.json')
df_json = pd.read_json('employees.json')
df_json

      name department  salary        city  experience
0  Yasmine    Nursing    6000       Rabat           8
1     Omar      Admin    4500  Casablanca           2
2     Sara   Pharmacy    7200       Rabat           5
3   Khalid    Nursing    6000         Fes           1
4    Imane      Admin    4500  Casablanca           6
5    Hamza   Pharmacy    7200       Rabat           9
6     Lina    Nursing    6000         Fes           3

2. Write df to SQLite database clinic.db as table 'employees', then read it back with pd.read_sql().

In [ ]:
import sqlite3

# Connect (creates file if doesn't exist)
conn = sqlite3.connect('clinic.db')

# Write DataFrame to SQL table
df.to_sql('employees', conn, if_exists='replace', index=False)

# Read back with SQL query — same as MySQL
df_sql = pd.read_sql('SELECT * FROM employees', conn)

df_sql

# Always close connection
conn.close()
df_sql

      name department  salary  experience
0  Yasmine    Nursing    6000           8
1     Omar      Admin    4500           2
2     Sara   Pharmacy    7200           5
3   Khalid    Nursing    6000           1
4    Imane      Admin    4500           6

Ex 3 — Simple Explanation
The scenario: a client sends you one Excel file with two sheets inside it:

Sheet 1: senior_staff (experience >= 5)

Sheet 2: junior_staff (experience < 5)

You need to:

Read both sheets
Combine them into one DataFrame
Add a column showing which level each person is
Save as one clean CSV

In [ ]:
# Step 1 — read each sheet separately
df_senior = pd.read_excel('staff.xlsx', sheet_name='senior_staff')
df_junior = pd.read_excel('staff.xlsx', sheet_name='junior_staff')

# Step 2 — add level column BEFORE combining
df_senior['level'] = 'senior'
df_junior['level'] = 'junior'

# Step 3 — combine into one DataFrame
df_full = pd.concat([df_senior, df_junior], ignore_index=True)

# Step 4 — save as CSV
df_full.to_csv('full_staff.csv', index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'staff.xlsx'