<a href="https://colab.research.google.com/github/fatidevt/data-skills-journey/blob/main/pandas/tutorial_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/DATASETS/results_2025.csv')
schema_df = pd.read_csv("/content/drive/MyDrive/DATASETS/schema_2025.csv")

/tmp/ipykernel_3636/2560097504.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('/content/drive/MyDrive/DATASETS/results_2025.csv')

In [ ]:
df1

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df1.shape #it's an attribute

(49191, 172)

In [ ]:
df1.info() #it's a methode

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [ ]:
pd.set_option('display.max_columns', 172)
pd.set_option('display.max_rows', 139)

In [ ]:
df1

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

**Schema to know each column mean to the dataset**

In [ ]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
10,QID18,TechEndorse_13_TEXT,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
11,QID19,TechOppose_1,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
12,QID19,TechOppose_2,What would turn you off or cause you to reject...,RO,Poor usability,2.0
13,QID19,TechOppose_3,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
14,QID19,TechOppose_5,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
15,QID19,TechOppose_7,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
16,QID19,TechOppose_9,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
17,QID19,TechOppose_11,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
18,QID19,TechOppose_13,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
19,QID19,TechOppose_16,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
20,QID19,TechOppose_15,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
21,QID19,TechOppose_15_TEXT,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
22,QID27,JobSatPoints_1,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
23,QID27,JobSatPoints_2,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
24,QID27,JobSatPoints_16,Rank the following attributes of your current ...,RO,You like your manager,3.0
25,QID27,JobSatPoints_3,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
26,QID27,JobSatPoints_4,Rank the following attributes of your current ...,RO,Expert mentors,5.0
27,QID27,JobSatPoints_5,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
28,QID27,JobSatPoints_6,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
29,QID27,JobSatPoints_7,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
30,QID27,JobSatPoints_8,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
31,QID27,JobSatPoints_9,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
32,QID27,JobSatPoints_10,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
33,QID27,JobSatPoints_11,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
34,QID27,JobSatPoints_13,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
35,QID27,JobSatPoints_14,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
36,QID27,JobSatPoints_15,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
37,QID27,JobSatPoints_15_TEXT,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
38,QID76,SO_Actions_1,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
39,QID76,SO_Actions_16,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
40,QID76,SO_Actions_3,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
41,QID76,SO_Actions_4,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
42,QID76,SO_Actions_5,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
43,QID76,SO_Actions_6,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
44,QID76,SO_Actions_9,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
45,QID76,SO_Actions_7,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
46,QID76,SO_Actions_10,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
47,QID76,SO_Actions_15,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
48,QID76,SO_Actions_15_TEXT,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
49,QID3,MainBranch,Are you someone who writes code? Please select...,MC,NaN,NaN
50,QID4,Age,What is your age?,MC,NaN,NaN
51,QID9,EdLevel,Which of the following best describes the high...,MC,NaN,NaN
52,QID7,Employment,Which of the following best describes your cur...,MC,NaN,NaN
53,QID8,EmploymentAddl,Which of the following <strong>additional</str...,MC,NaN,NaN
54,QID14,WorkExp,How many years of professional work experience...,TE,NaN,NaN
55,QID10,LearnCodeChoose,Did you begin learning to code or learn a new ...,MC,NaN,NaN
56,QID11,LearnCode,How did you learn to code in the past year? Se...,MC,NaN,NaN
57,QID12,LearnCodeAI,Did you spend time in the last year learning A...,MC,NaN,NaN
58,QID32,AILearnHow,How did you learn to code for AI in the past y...,MC,NaN,NaN
59,QID13,YearsCode,"Including any education, how many years have y...",TE,NaN,NaN
60,QID15,DevType,Which of the following describes your current ...,MC,NaN,NaN
61,QID16,OrgSize,Approximately how many people are employed by ...,MC,NaN,NaN
62,QID23,ICorPM,Are you an individual contributor or people ma...,MC,NaN,NaN
63,QID24,RemoteWork,Which best describes your current work situation?,MC,NaN,NaN
64,QID17,PurchaseInfluence,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
65,QID33,TechEndorseIntro,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
66,QID25,Industry,What industry do you work for in?,MC,NaN,NaN
67,QID26,JobSat,How satisfied are you in your current professi...,MC,NaN,NaN
68,QID28,AIThreat,Do you believe AI is a threat to your current ...,MC,NaN,NaN
69,QID29,NewRole,Have you considered a career change or transit...,MC,NaN,NaN
70,QID30,ToolCountWork,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
71,QID31,ToolCountPersonal,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
72,QID20,Country,Where do you live?,MC,NaN,NaN
73,QID21,Currency,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
74,QID22,CompTotal,What is your current total <b>annual</b> compe...,TE,NaN,NaN
75,QID44,LanguageChoice,"Did you work with programming, scripting and m...",MC,NaN,NaN
76,QID34,Language,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
77,QID51,LanguagesHaveEntry,Was the programming language you use not liste...,TE,NaN,NaN
78,QID52,LanguagesWantEntry,Was the programming language you want to use n...,TE,NaN,NaN
79,QID45,DatabaseChoice,Did you work with database environments in the...,MC,NaN,NaN
80,QID35,Database,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
81,QID54,DatabaseHaveEntry,Was the database environment you use not liste...,TE,NaN,NaN
82,QID55,DatabaseWantEntry,Was the database environment you want to use n...,TE,NaN,NaN
83,QID46,PlatformChoice,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
84,QID36,Platform,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
85,QID56,PlatformHaveEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
86,QID57,PlatformWantEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
87,QID47,WebframeChoice,Did you work with web frameworks and web techn...,MC,NaN,NaN
88,QID37,Webframe,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
89,QID58,WebframeHaveEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
90,QID59,WebframeWantEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
91,QID48,DevEnvsChoice,Did you work with development environments or ...,MC,NaN,NaN
92,QID38,DevEnvs,Which <strong>development environments and AI-...,Matrix,NaN,NaN
93,QID60,DevEnvHaveEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
94,QID61,DevEnvWantEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
95,QID39,SOTags,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
96,QID62,SOTagsHaveEntry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
97,QID63,SOTagsWant Entry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
98,QID40,OpSys,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
99,QID41,OfficeStackAsync,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
100,QID64,OfficeStackHaveEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
101,QID65,OfficeStackWantEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
102,QID42,CommPlatform,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
103,QID66,CommPlatformHaveEntr,Was the community platform you use not listed ...,TE,NaN,NaN
104,QID67,CommPlatformWantEntr,Was the community platform you want to use not...,TE,NaN,NaN
105,QID50,AIModelsChoice,Did you utilize or integrate specific Large La...,MC,NaN,NaN
106,QID43,AIModels,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
107,QID68,AIModelsHaveEntry,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
108,QID69,AIModelsWantEntry,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
109,QID72,SOAccount,Do you have a Stack Overflow account?,MC,NaN,NaN
110,QID70,SOVisitFreq,How frequently would you say you visit Stack O...,MC,NaN,NaN
111,QID71,SODuration,How long have you used Stack Overflow?,MC,NaN,NaN
112,QID73,SOPartFreq,How frequently would you say you participate i...,MC,NaN,NaN
113,QID75,SO_Dev_Content,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
114,QID77,SOComm,Do you consider yourself a member of the Stack...,MC,NaN,NaN
115,QID97,SOFriction,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
116,QID78,AISelect,Do you currently use AI tools in your developm...,MC,NaN,NaN
117,QID79,AISent,How favorable is your stance on using AI tools...,MC,NaN,NaN
118,QID80,AIAcc,How much do you trust the accuracy of the outp...,MC,NaN,NaN
119,QID81,AIComplex,How well do the AI tools you use in your devel...,MC,NaN,NaN
120,QID82,AITool,Which parts of your development workflow are y...,Matrix,NaN,NaN
121,QID99,AIFrustration,"When using AI tools, which of the following pr...",MC,NaN,NaN
122,QID84,AIExplain,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
123,QID85,AIAgents,Are you using AI agents in your work (developm...,MC,NaN,NaN
124,QID83,AIAgentChange,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
125,QID86,AIAgent_Uses,What industry purposes or specific tasks are y...,MC,NaN,NaN
126,QID106,AgentUsesGeneral,,MC,NaN,NaN
127,QID87,AIAgentImpact,To what extent do you agree with the following...,Matrix,NaN,NaN
128,QID88,AIAgentChallenges,To what extent do you agree with the following...,Matrix,NaN,NaN
129,QID89,AIAgentKnowledge,You indicated you use or develop AI agents as ...,MC,NaN,NaN
130,QID107,AIAgentKnowWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
131,QID90,AIAgentOrchestration,You indicated you use or develop AI agents as ...,MC,NaN,NaN
132,QID102,AIAgentOrchWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
133,QID91,AIAgentObserveSecure,You indicated you use or develop AI agents as ...,MC,NaN,NaN
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [ ]:
schema_df.shape

(139, 6)

In [ ]:
pd.set_option('display.max_rows', 139)

In [ ]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
10,QID18,TechEndorse_13_TEXT,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
11,QID19,TechOppose_1,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
12,QID19,TechOppose_2,What would turn you off or cause you to reject...,RO,Poor usability,2.0
13,QID19,TechOppose_3,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
14,QID19,TechOppose_5,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
15,QID19,TechOppose_7,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
16,QID19,TechOppose_9,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
17,QID19,TechOppose_11,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
18,QID19,TechOppose_13,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
19,QID19,TechOppose_16,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
20,QID19,TechOppose_15,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
21,QID19,TechOppose_15_TEXT,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
22,QID27,JobSatPoints_1,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
23,QID27,JobSatPoints_2,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
24,QID27,JobSatPoints_16,Rank the following attributes of your current ...,RO,You like your manager,3.0
25,QID27,JobSatPoints_3,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
26,QID27,JobSatPoints_4,Rank the following attributes of your current ...,RO,Expert mentors,5.0
27,QID27,JobSatPoints_5,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
28,QID27,JobSatPoints_6,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
29,QID27,JobSatPoints_7,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
30,QID27,JobSatPoints_8,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
31,QID27,JobSatPoints_9,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
32,QID27,JobSatPoints_10,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
33,QID27,JobSatPoints_11,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
34,QID27,JobSatPoints_13,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
35,QID27,JobSatPoints_14,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
36,QID27,JobSatPoints_15,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
37,QID27,JobSatPoints_15_TEXT,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
38,QID76,SO_Actions_1,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
39,QID76,SO_Actions_16,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
40,QID76,SO_Actions_3,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
41,QID76,SO_Actions_4,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
42,QID76,SO_Actions_5,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
43,QID76,SO_Actions_6,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
44,QID76,SO_Actions_9,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
45,QID76,SO_Actions_7,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
46,QID76,SO_Actions_10,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
47,QID76,SO_Actions_15,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
48,QID76,SO_Actions_15_TEXT,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
49,QID3,MainBranch,Are you someone who writes code? Please select...,MC,NaN,NaN
50,QID4,Age,What is your age?,MC,NaN,NaN
51,QID9,EdLevel,Which of the following best describes the high...,MC,NaN,NaN
52,QID7,Employment,Which of the following best describes your cur...,MC,NaN,NaN
53,QID8,EmploymentAddl,Which of the following <strong>additional</str...,MC,NaN,NaN
54,QID14,WorkExp,How many years of professional work experience...,TE,NaN,NaN
55,QID10,LearnCodeChoose,Did you begin learning to code or learn a new ...,MC,NaN,NaN
56,QID11,LearnCode,How did you learn to code in the past year? Se...,MC,NaN,NaN
57,QID12,LearnCodeAI,Did you spend time in the last year learning A...,MC,NaN,NaN
58,QID32,AILearnHow,How did you learn to code for AI in the past y...,MC,NaN,NaN
59,QID13,YearsCode,"Including any education, how many years have y...",TE,NaN,NaN
60,QID15,DevType,Which of the following describes your current ...,MC,NaN,NaN
61,QID16,OrgSize,Approximately how many people are employed by ...,MC,NaN,NaN
62,QID23,ICorPM,Are you an individual contributor or people ma...,MC,NaN,NaN
63,QID24,RemoteWork,Which best describes your current work situation?,MC,NaN,NaN
64,QID17,PurchaseInfluence,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
65,QID33,TechEndorseIntro,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
66,QID25,Industry,What industry do you work for in?,MC,NaN,NaN
67,QID26,JobSat,How satisfied are you in your current professi...,MC,NaN,NaN
68,QID28,AIThreat,Do you believe AI is a threat to your current ...,MC,NaN,NaN
69,QID29,NewRole,Have you considered a career change or transit...,MC,NaN,NaN
70,QID30,ToolCountWork,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
71,QID31,ToolCountPersonal,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
72,QID20,Country,Where do you live?,MC,NaN,NaN
73,QID21,Currency,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
74,QID22,CompTotal,What is your current total <b>annual</b> compe...,TE,NaN,NaN
75,QID44,LanguageChoice,"Did you work with programming, scripting and m...",MC,NaN,NaN
76,QID34,Language,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
77,QID51,LanguagesHaveEntry,Was the programming language you use not liste...,TE,NaN,NaN
78,QID52,LanguagesWantEntry,Was the programming language you want to use n...,TE,NaN,NaN
79,QID45,DatabaseChoice,Did you work with database environments in the...,MC,NaN,NaN
80,QID35,Database,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
81,QID54,DatabaseHaveEntry,Was the database environment you use not liste...,TE,NaN,NaN
82,QID55,DatabaseWantEntry,Was the database environment you want to use n...,TE,NaN,NaN
83,QID46,PlatformChoice,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
84,QID36,Platform,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
85,QID56,PlatformHaveEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
86,QID57,PlatformWantEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
87,QID47,WebframeChoice,Did you work with web frameworks and web techn...,MC,NaN,NaN
88,QID37,Webframe,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
89,QID58,WebframeHaveEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
90,QID59,WebframeWantEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
91,QID48,DevEnvsChoice,Did you work with development environments or ...,MC,NaN,NaN
92,QID38,DevEnvs,Which <strong>development environments and AI-...,Matrix,NaN,NaN
93,QID60,DevEnvHaveEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
94,QID61,DevEnvWantEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
95,QID39,SOTags,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
96,QID62,SOTagsHaveEntry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
97,QID63,SOTagsWant Entry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
98,QID40,OpSys,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
99,QID41,OfficeStackAsync,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
100,QID64,OfficeStackHaveEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
101,QID65,OfficeStackWantEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
102,QID42,CommPlatform,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
103,QID66,CommPlatformHaveEntr,Was the community platform you use not listed ...,TE,NaN,NaN
104,QID67,CommPlatformWantEntr,Was the community platform you want to use not...,TE,NaN,NaN
105,QID50,AIModelsChoice,Did you utilize or integrate specific Large La...,MC,NaN,NaN
106,QID43,AIModels,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
107,QID68,AIModelsHaveEntry,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
108,QID69,AIModelsWantEntry,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
109,QID72,SOAccount,Do you have a Stack Overflow account?,MC,NaN,NaN
110,QID70,SOVisitFreq,How frequently would you say you visit Stack O...,MC,NaN,NaN
111,QID71,SODuration,How long have you used Stack Overflow?,MC,NaN,NaN
112,QID73,SOPartFreq,How frequently would you say you participate i...,MC,NaN,NaN
113,QID75,SO_Dev_Content,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
114,QID77,SOComm,Do you consider yourself a member of the Stack...,MC,NaN,NaN
115,QID97,SOFriction,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
116,QID78,AISelect,Do you currently use AI tools in your developm...,MC,NaN,NaN
117,QID79,AISent,How favorable is your stance on using AI tools...,MC,NaN,NaN
118,QID80,AIAcc,How much do you trust the accuracy of the outp...,MC,NaN,NaN
119,QID81,AIComplex,How well do the AI tools you use in your devel...,MC,NaN,NaN
120,QID82,AITool,Which parts of your development workflow are y...,Matrix,NaN,NaN
121,QID99,AIFrustration,"When using AI tools, which of the following pr...",MC,NaN,NaN
122,QID84,AIExplain,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
123,QID85,AIAgents,Are you using AI agents in your work (developm...,MC,NaN,NaN
124,QID83,AIAgentChange,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
125,QID86,AIAgent_Uses,What industry purposes or specific tasks are y...,MC,NaN,NaN
126,QID106,AgentUsesGeneral,,MC,NaN,NaN
127,QID87,AIAgentImpact,To what extent do you agree with the following...,Matrix,NaN,NaN
128,QID88,AIAgentChallenges,To what extent do you agree with the following...,Matrix,NaN,NaN
129,QID89,AIAgentKnowledge,You indicated you use or develop AI agents as ...,MC,NaN,NaN
130,QID107,AIAgentKnowWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
131,QID90,AIAgentOrchestration,You indicated you use or develop AI agents as ...,MC,NaN,NaN
132,QID102,AIAgentOrchWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
133,QID91,AIAgentObserveSecure,You indicated you use or develop AI agents as ...,MC,NaN,NaN
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [ ]:
df1.head(7)
#by default it gives 5 rows

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,20.0,"Developer, back-end",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Work,12.0,5.0,4.0,6.0,2.0,10.0,3.0,7.0,8.0,14.0,NaN,12.0,5.0,13.0,10.0,9.0,1.0,4.0,6.0,2.0,15.0,NaN,Fintech,4.0,3.0,5.0,8.0,9.0,2.0,1.0,10.0,11.0,12.0,6.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,5.0,Ukraine,USD United States dollar,120000.0,Yes,Java;Scala,Java;Kotlin;Scala,Java;Scala,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Amazon Web Services (AWS),Amazon Web Services (AWS),NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,akka,akka,Yes,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS,MacOS,Azure Devops;GitHub;GitLab;Jira,GitHub;Jira,GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year","Lists of recommendations (tools, frameworks, t...",6.0,NaN,9.0,3.0,4.0,5.0,10.0,1.0,11.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Predictive analytics,Deployment and monitoring,Project planning;Debugging or fixing code;Comm...,Testing code;Learning new concepts or technolo...,"AI solutions that are almost right, but not quite",No it isnt,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,NaN,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0

In [ ]:
df1.tail(7)
#by default it gives 5 rows

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
49184,49185,"I am not primarily a developer, but I write co...",45-54 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,"Caring for dependents (children, elderly, etc....",30.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49185,49186,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49189,49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,6.0,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# VIDEO 2 : DataFrame and Series Basics

In [ ]:
people = {
    "first": ["John", "Alice", "Bob" , "Amina"],
    "last": ["Smith", "Johnson", "Brown" , "Brown"],
    "email": [
        "john.smith@example.com",
        "alice.johnson@example.com",
        "bob.brown@example.com",
        "amina.brown@example.com"
    ]
}


*   DataFrame = rows and columns

*   Series = rows of a single columns


*   DataFrame ==> df = pd.DataFrame(people)

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(people)

In [ ]:
df

   first     last                      email
0   John    Smith     john.smith@example.com
1  Alice  Johnson  alice.johnson@example.com
2    Bob    Brown      bob.brown@example.com
3  Amina    Brown    amina.brown@example.com


*   series ==> df.email or df['email'] (recommendation)

*   access multiple series ==> df[['first' , 'email']]

In [ ]:
df['email']

0       john.smith@example.com
1    alice.johnson@example.com
2        bob.brown@example.com
3      amina.brown@example.com
Name: email, dtype: object

In [ ]:
df[[ 'first' , 'email' ]]

   first                      email
0   John     john.smith@example.com
1  Alice  alice.johnson@example.com
2    Bob      bob.brown@example.com
3  Amina    amina.brown@example.com

In [ ]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

**To access rows we use iloc / loc**

iloc : integer location

arguments : row + column

In [ ]:
df

   first     last                      email
0   John    Smith     john.smith@example.com
1  Alice  Johnson  alice.johnson@example.com
2    Bob    Brown      bob.brown@example.com
3  Amina    Brown    amina.brown@example.com

In [ ]:
#first row
df.iloc[0]

first                      John
last                      Smith
email    john.smith@example.com
Name: 0, dtype: object

In [ ]:
#many rows
df.iloc [[1,2]]

   first     last                      email
1  Alice  Johnson  alice.johnson@example.com
2    Bob    Brown      bob.brown@example.com

In [ ]:
# row , column
df.iloc[1 , 2]

'alice.johnson@example.com'

In [ ]:
df.iloc[[1 , 2] , 2]

1    alice.johnson@example.com
2        bob.brown@example.com
Name: email, dtype: object

loc = row + 'column_name' (string)

In [ ]:
df

   first     last                      email
0   John    Smith     john.smith@example.com
1  Alice  Johnson  alice.johnson@example.com
2    Bob    Brown      bob.brown@example.com
3  Amina    Brown    amina.brown@example.com

In [ ]:
df.loc[1, 'email']

'alice.johnson@example.com'

In [ ]:
df.loc[ [1 , 2] , ['email' , 'last'] ]

                       email     last
1  alice.johnson@example.com  Johnson
2      bob.brown@example.com    Brown

# Application to dataset

In [ ]:
df1.shape

(49191, 172)

In [ ]:
schema_df.shape

(139, 6)

In [ ]:
pd.set_option('display.max_columns', 172)
pd.set_option('display.max_rows', 139)

In [ ]:
df1.head()

In [ ]:
df1.columns

In [ ]:
schema_df

Get all resposes af column RemoteWork

In [ ]:
#df['column_name']
df1['RemoteWork']

In [ ]:
df1['AIAgentKnowledge'].value_counts()

How many of the responses are "yes" and how many "no"

In [ ]:
df1['RemoteWork'].value_counts()

# loc

In [ ]:
# row 3 , column RemoteWork
df1.loc[ 3 , 'RemoteWork' ]

In [ ]:
#slicing : don't use []
# the last value is inclusif
df1.loc[ 0:2 , 'MainBranch':'WorkExp' ]

In [ ]:
df1['LearnCodeChoose']

# Video 3 : Indexes

In [ ]:
# set the email as the index of the dataset (but this will not change the original dataset)
df.set_index('email')

In [ ]:
# to make the email as the index of the dataset + change the dataset
df.set_index('email' , inplace=True)

In [ ]:
df

In [ ]:
# the index of the dataframe
df.index

In [ ]:
df.loc['john.smith@example.com']

In [ ]:
# reset the default index methode
df.reset_index(inplace=True)

In [ ]:
df

# Application On The Dataset

In [ ]:
df1

In [ ]:
# for csv we can add an argument to make the set the index
df1 = pd.read_csv('/content/drive/MyDrive/DATASETS/results_2025.csv' , index_col='ResponseId')

In [ ]:
# now the ResponseId is the index
df1.head()

In [ ]:
schema_df

In [ ]:
# making the column name is the index of schema csv
schema_df = pd.read_csv("/content/drive/MyDrive/DATASETS/schema_2025.csv" , index_col="qname")

In [ ]:
schema_df.head()

In [ ]:
pd.set_option('display.max_colwidth', None)

In [ ]:
schema_df.loc['AILearnHow' , 'question' ]

In [ ]:
# sort the index column (by default acsending = 'True')
schema_df.sort_index()

In [ ]:
schema_df

In [ ]:
schema_df.loc['AIAcc' , 'question']

In [ ]:
schema_df.sort_index(ascending=False)

In [ ]:
df1.head()

In [ ]:
df1.loc[ 1:7 , 'WorkExp']

Golden rule:

.loc  → thinks in LABELS

.iloc → thinks in POSITIONS

# Video 4 : Filtering - Using Conditionals to Filter Rows and Columns

In [ ]:
df

In [ ]:
filt = (df['last'] == 'Brown')

In [ ]:
#df[ df['last'] == 'Brown' ]
df[filt]

In [ ]:
# the emails of the filterd columns
df.loc[filt , 'email']

In [ ]:
# & ==> and
# | ==> or
filt1 = (df['last'] == 'Brown') & (df['first'] == 'Amina')
df[filt1]

In [ ]:
df[filt1]

In [ ]:
df.loc[filt1]

In [ ]:
df

In [ ]:
filt2 = (df['first'] == 'John' ) | ( df['last'] == 'Brown' )

In [ ]:
df.loc[filt2, 'email']

In [ ]:
# Opposit ==> ~ fliter
df.loc[~filt2 , 'email']

# Application On The Dataset

In [ ]:
high_salary = (df1['ConvertedCompYearly'] >= 70000)

In [ ]:
df1[high_salary]

In [ ]:
df1.loc[high_salary, ['Country' ,'LanguageHaveWorkedWith' , 'ConvertedCompYearly' ]]

In [ ]:
countries = ['United States', 'India' , 'United Kingdom' , 'Germany' , 'Canada']
filt3 = df1['Country'].isin(countries)

In [ ]:
df1.loc[filt3 , ['Country' ,'LanguageHaveWorkedWith' , 'ConvertedCompYearly' ]]

In [ ]:
filt4 = df1['LanguageHaveWorkedWith'].str.contains('Python' , na=False)
df1[filt4]

df[df['col'] > 5]          # works, but you CAN'T filter rows AND select columns at once

df.loc[df['col'] > 5, 'name']   # filter rows AND pick column(s) in one shot

df.loc[df['col'] > 5, ['name', 'age']]  # or multiple columns

# Video 5 : Updating Rows and Columns - Modifying Data Within

In [ ]:
df

In [ ]:
df.columns

In [ ]:
# Edit columns names
df.columns = ['first_name' , 'last_name', 'email']
df

In [ ]:
# change to lower or upper
df.columns = [ x.lower() for x in df.columns ]
df

In [ ]:
#remove spaces an replace with _
df.columns = df.columns.str.replace('_' , '-')
df

In [ ]:
df.columns

In [ ]:
# Rename the columns names
df = df.rename(columns = {'first-name' : 'name' , 'last-name' : 'last'})
df

In [ ]:
# Changing one or multiple values with loc
df.loc[3] = ['Amina' , 'Fridi' , 'amina.fridi@example.com	']
df

In [ ]:
#Changing one or multiple values
df.loc[3 , ['email' , 'last']] = ['amina.fridi@example.com' , 'FRIDI']
df

In [ ]:
# Changing a single cell value
df.at[3, 'last'] = 'AFRIDI'
df

In [ ]:
filt = df['email'] == 'amina.fridi@example.com'
df.loc[filt, 'name'] = 'Ni3ma'
df

In [ ]:
# make a column values lower
df['email'] = df['email'].str.lower()
df

In [ ]:
# make a column values title case
df['last'] = df['last'].str.title()
df

In [ ]:
df

In [ ]:
#apply function
#nb of cara of each email
df['email'].apply(len)

In [ ]:
#function to upper case the emails
def email_upper(email):
  return email.upper()

In [ ]:
df['email'].apply(email_upper)

In [ ]:
df['email'] = df['email'].apply(email_upper)

In [ ]:
df

In [ ]:
#apply function with lambda
# lower case emails
df['email'].apply(lambda x: x.lower())

In [ ]:
df['email'] = df['email'].apply(lambda x: x.lower())
df

In [ ]:
df

In [ ]:
df.columns

In [ ]:
df['name'] = ['John' , 'Alice', 'Bob' , 'Amina']
df

In [ ]:
#apply func applied on series if we use df
# Number of rows in the table
df.apply(len)

In [ ]:
#apply func applied on series if we use df
# Number of columns in the table
df.apply(len, axis = 'columns')

In [ ]:
# apply func applied on column's values if we use col_name
# Number of characters in each string
df['name'].apply(len)

In [ ]:
#df.applymap() applies a function to every single cell in your entire DataFrame individually
df.applymap(len)

In [ ]:
df = df.applymap(str.lower)
df

In [ ]:
# The values stay the same if unlisted values
df['name'].replace({'john' : 'mikle'})

In [ ]:
df

In [ ]:
# The values become NaN if unlisted values
df['name'].map({'john' : 'didi'})

# Video 6 : Add/Remove Rows and Columns From DataFrames

In [ ]:
data = {
    "first": ["John", "Alice", "Bob" , "Amina"],
    "last": ["Smith", "Johnson", "Brown" , "Brown"],
    "email": [
        "john.smith@example.com",
        "alice.johnson@example.com",
        "bob.brown@example.com",
        "amina.brown@example.com"
    ]
}
df6 = pd.DataFrame(data)
df6

In [ ]:
df6['full_name'] = df6['first'] + ' ' + df6['last']

In [ ]:
df6

In [ ]:
df6.drop(columns=['first' , 'last'] , inplace=True)

In [ ]:
df6

In [ ]:
df6['full_name'].str.split(' ')
# give us list : [John,Smith]

In [ ]:
df6['full_name'].str.split(' ', expand=True)
# give us list : 2 columns separated instead of list

In [ ]:
df6

In [ ]:
df6[['first','last']] = df6['full_name'].str.split(' ', expand=True)

In [ ]:
df6

In [ ]:
pd.__version__

In [ ]:
df6

In [ ]:
#add row
new_row = pd.DataFrame([{'first': 'Youssef', 'last': 'Kennani'}])
df6 = pd.concat([df6, new_row], ignore_index=True)

In [ ]:
df6

In [ ]:
#remove row
df6 = df6.drop(index=4)

In [ ]:
df6

In [ ]:
#remove row with condition
filt = df6['first'] == 'Alice'
df6 = df6.drop(index=df6[filt].index)

In [ ]:
df6

# Part 7 : Sorting Data

In [ ]:
import pandas as pd
data = {
    'first': ['Amina', 'Bahia', 'Camilia', 'Daniel', 'Erem'],
    'last': ['Alami', 'Bouaddi', 'Bouaddi', 'Bouaddi', 'Enwawr'],
    'email': ['amina@email.com', 'Bahia@email.com', 'Camilia@email.com', 'Daniel@email.com', 'Erem@email.com']
}
df7 = pd.DataFrame(data)
df7

In [ ]:
df7.sort_values(by='first', ascending=False)

In [ ]:
df7.sort_values(by=['first','last'], ascending=[False, True] , inplace=True)

In [ ]:
df7

# Part 8 : Grouping and Aggregating - Analyzing and Exploring

aggregation : combine mupltiple pcs of data into single result (ex: mean, max, min ..)

In [ ]:
df1

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community)","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantial addition to the tech stack",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a new career or industry,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;Google Cloud;Gradle,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn;Medium",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image generating models;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Overflow,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search for answers,Project planning;Deployment and monitoring;Learning new concepts or technologies,Documenting code;Debugging or fixing code;Testing code;Committing and reviewing code;Predictive analytics;Generating content or synthetic data;Creating or maintaining documentation,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI agents have reduced the time spent on specific development tasks.,AI agents have helped me automate repetitive tasks.;AI agents have improved the quality of my code.;AI agents have accelerated my learning about new technologies or codebases.;AI agents have helped me solve complex problems more effectively.;AI agents have improved collaboration within my team.,NaN,NaN,NaN,I am concerned about the accuracy of the information provided by AI agents.;It takes significant time and effort to learn how to use AI agents effectively.,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security and privacy of data when using AI agents.,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibility)",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or industry voluntarily,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,Amazon Web Services (AWS);Datadog;Docker;Homebrew;Kubernetes;Maven (build tool);Terraform,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,"Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;Twitch;LinkedIn;Substack;Medium","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;Twitch;LinkedIn;Substack;Medium","Stack Overflow;Discord;Reddit;Dev.to;Hacker News;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;Twitch;LinkedIn;Substack;Medium",NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year","Chat (people);Message Boards;Long-form articles;Videos;Coding challenges;Logic games/puzzles;Lists of recommendations (tools, frameworks, technologies, etc.);Direct messaging of users;Job board;Day-in-the-life profiles/interviews with experts",6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Committing and reviewing code;Deployment and monitoring,Writing code;Documenting code;Debugging or fixing code;Testing code;Predictive analytics;Search for answers;Generating content or synthetic data;Creating or maintaining documentation,NaN,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns about the security and privacy of data when using AI agents.,Integrating AI agents with my existing tools and workflows can be difficult.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I want to compare different solutions;When I have ethical or security concerns about code,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-employed",None of the above,10.0,"Yes, I am not new to coding but am learning new coding techniques or programming language",Online Courses or Certification (includes all media types);Videos (not associated with specific online course or certification);Technical documentation (is generated for/by the tool or system),"Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies",AI CodeGen tools or AI-enabled apps;Technical documentation (is generated for/by the tool or system);Videos (not associated with specific online course or certification),12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or industry involuntarily,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI GPT (chatbot models),Gemini (Flash general purpose models);Gemini (Pro Reasoning models);openAI GPT (chatbot models),Gemini (Flash general purpose models);openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year","Chat (people);Videos;Lists of recommendations (tools, frameworks, technologies, etc.);Chat (bot/AI)",3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Testing code;Creating or maintaining documentation;Learning new concepts or technologies,NaN,Project planning;Committing and reviewing code;Deployment and monitoring;Predictive analytics;Search for answers,Learning about a codebase;Writing code;Generating content or synthetic data,NaN,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI agents have helped me automate repetitive tasks.;AI agents have accelerated my learning about new technologies or codebases.;AI agents have reduced the time spent on specific development tasks.,AI agents have improved the quality of my code.;AI agents have helped me solve complex problems more effectively.,AI agents have improved collaboration within my team.,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,I am concerned about the accuracy of the information provided by AI agents.;Integrating AI agents with my existing tools and workflows can be difficult.;I have concerns about the security and privacy of data when using AI agents.,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem,"Understand how things actually work, problem solving, and algorithms",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);AI CodeGen tools or AI-enabled apps","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies","AI CodeGen tools or AI-enabled apps;Videos (not associated with specific online course or certification);Other online resources (e.g. standard search, forum, online community)",5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a new career or industry,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Overflow,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code;Committing and reviewing code;Deployment and monitoring;Creating or maintaining documentation,Learning about a codebase;Writing code;Debugging or fixing code;Predictive analytics,Search for answers;Generating content or synthetic data;Learning new concepts or technologies,NaN,"AI solutions that are almost right, but not quite;I don’t use AI tools regularly",NO,"Yes, I use AI agents at work monthly or infrequently",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about new technologies or codebases.,AI agents have increased my productivity.;AI agents have improved the quality of my code.;AI agents have helped me solve complex problems more effectively.;AI agents have reduced the time spent on specific development tasks.;AI agents have improved collaboration within my team.,AI agents have helped me automate repetitive tasks.,NaN,NaN,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,NaN,I am concerned about the accuracy of the information provided by AI agents.;I have concerns about the security and privacy of data when using AI agents.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,Integrating AI agents with my existing tools and workflows can be difficult.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem,NaN,36197.0,6.0

In [ ]:
df1['ConvertedCompYearly'].head(50)

ResponseId
1      61256.0
2     104413.0
3      53061.0
4      36197.0
5      60000.0
6     120000.0
7       6240.0
8      72000.0
9      70000.0
10      5400.0
11     65691.0
12     14400.0
13      1099.0
14         NaN
15         NaN
16         NaN
17     16252.0
18         NaN
19         NaN
20         NaN
21         NaN
22         NaN
23     87500.0
24         NaN
25         NaN
26    108913.0
27    162421.0
28    209643.0
29     78000.0
30    205000.0
31         NaN
32    250000.0
33         NaN
34    175000.0
35         NaN
36     95132.0
37         NaN
38    109000.0
39     91215.0
40    150000.0
41     99999.0
42    270000.0
43    250000.0
44     43810.0
45         NaN
46     80966.0
47         NaN
48     28275.0
49    142949.0
50    117793.0
Name: ConvertedCompYearly, dtype: float64

In [ ]:
df1['ConvertedCompYearly'].median()

75320.0

In [ ]:
df1.median(numeric_only=True)

WorkExp                    10.0
YearsCode                  14.0
TechEndorse_1               9.0
TechEndorse_2               4.0
TechEndorse_3               4.0
TechEndorse_4               6.0
TechEndorse_5               4.0
TechEndorse_6               5.0
TechEndorse_7               7.0
TechEndorse_8               4.0
TechEndorse_9               4.0
TechEndorse_13             10.0
TechOppose_1                9.0
TechOppose_2                4.0
TechOppose_3                6.0
TechOppose_5                5.0
TechOppose_7                4.0
TechOppose_9                3.0
TechOppose_11               4.0
TechOppose_13               5.0
TechOppose_16               6.0
TechOppose_15              10.0
JobSatPoints_1              6.0
JobSatPoints_2              4.0
JobSatPoints_3              7.0
JobSatPoints_4             10.0
JobSatPoints_5             10.0
JobSatPoints_6              8.0
JobSatPoints_7              5.0
JobSatPoints_8              7.0
JobSatPoints_9              6.0
JobSatPoints_10             7.0
JobSatPoints_11             5.0
JobSatPoints_13             9.0
JobSatPoints_14             9.0
JobSatPoints_15            15.0
JobSatPoints_16             8.0
ToolCountWork               6.0
ToolCountPersonal           5.0
CompTotal              105000.0
SO_Actions_1                5.0
SO_Actions_16               2.0
SO_Actions_3                6.0
SO_Actions_4                4.0
SO_Actions_5                5.0
SO_Actions_6                5.0
SO_Actions_9                6.0
SO_Actions_7                5.0
SO_Actions_10               8.0
SO_Actions_15              10.0
ConvertedCompYearly     75320.0
JobSat                      8.0
dtype: float64

In [ ]:
#STATISTICS OF NUMERCI COLUMNS
df1.describe()

,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,ToolCountWork,ToolCountPersonal,CompTotal,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,ConvertedCompYearly,JobSat
count,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,27611.000000,25582.000000,2.486600e+04,26260.000000,24340.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,4.370841,4.431661,9.854315,8.307948,4.524067,5.925567,4.991710,4.048980,3.799323,4.365831,5.059867,5.508538,9.945766,6.867738,5.216173,7.455719,9.537947,9.758209,8.194965,5.884096,7.367799,6.744658,7.512569,5.703283,8.563324,8.679349,14.687487,7.826685,17.734852,8.545579,2.234198e+70,4.907845,3.339770,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,2.357058,2.620901,1.975692,2.202164,2.282867,2.301937,2.294707,2.607443,2.499468,2.557152,2.533541,2.906146,2.087463,3.741490,3.660632,3.726759,3.781286,3.557588,3.801257,3.900813,4.118532,3.888845,3.847265,4.110528,3.545288,3.633175,1.898188,4.077460,269.810134,44.664738,3.523096e+72,2.682204,2.411404,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,2.000000,2.000000,10.000000,8.000000,3.000000,4.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,10.000000,4.000000,2.000000,4.000000,7.000000,7.000000,5.000000,2.000000,4.000000,3.000000,4.000000,2.000000,6.000000,6.000000,15.000000,4.000000,4.000000,3.000000,5.500000e+04,3.000000,1.000000,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,4.000000,4.000000,10.000000,9.000000,4.000000,6.000000,5.000000,4.000000,3.000000,4.000000,5.000000,6.000000,10.000000,6.000000,4.000000,7.000000,10.000000,10.000000,8.000000,5.000000,7.000000,6.000000,7.000000,5.000000,9.000000,9.000000,15.000000,8.000000,6.000000,5.000000,1.050000e+05,5.000000,2.000000,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,6.000000,7.000000,10.000000,9.000000,6.000000,8.000000,7.000000,6.000000,6.000000,6.000000,7.000000,8.000000,10.000000,10.000000,8.000000,11.000000,13.000000,13.000000,11.000000,9.000000,11.000000,10.000000,11.000000,9.000000,12.000000,12.000000,15.000000,11.000000,10.000000,7.000000,2.400000e+05,7.000000,5.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.000000,15.000000,15.000000,16.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,10000.000000,1000.000000,5.555556e+74,15.000000,10.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [ ]:
df1['ConvertedCompYearly'].count()

np.int64(23947)

In [ ]:
country_grp = df1.groupby(['Country'])

In [ ]:
country_grp.get_group('Morocco')

/tmp/ipykernel_3636/3028068724.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  country_grp.get_group('Morocco')

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
267,I am a developer by profession,18-24 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),1.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Online Courses or Certification (includes all media types);Videos (not associated with specific online course or certification);School (i.e., University, College, etc)","Yes, I learned how to use AI-enabled tools required for my job or to benefit my career","Videos (not associated with specific online course or certification);Online Courses or Certification (includes all media types);School (i.e., University, College, etc)",4.0,"Developer, full-stack","10,000 or more employees",Individual contributor,Remote,No,Work,13.0,1.0,3.0,12.0,5.0,6.0,7.0,4.0,10.0,14.0,NaN,13.0,2.0,3.0,4.0,5.0,1.0,9.0,11.0,10.0,15.0,NaN,Manufacturing,13.0,4.0,6.0,3.0,7.0,12.0,1.0,9.0,2.0,14.0,5.0,10.0,11.0,15.0,8.0,NaN,No,I have strongly considered changing my career and/or the industry I work in,6.0,2.0,Morocco,MAD\tMoroccan dirham,114000.0,Yes,GDScript;HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;PostgreSQL;Redis;SQLite,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Digital Ocean;Docker;Kubernetes;npm;Pip;pnpm;Vite;Webpack,NaN,NaN,NaN,NaN,Yes,Django;FastAPI;Flask;Node.js;React;Vue.js,NaN,NaN,NaN,NaN,Yes,Android Studio;IntelliJ IDEA;PyCharm;Visual Studio Code,NaN,NaN,NaN,NaN,Large Language Model;RAG;Google Gemini,NaN,NaN,NaN,NaN,Ubuntu;Android;Linux (non-WSL),NaN,GitHub;GitLab;Google Colab;Jira;Markdown File,NaN,NaN,NaN,NaN,"Stack Overflow;Stack Exchange;Discord;Reddit;GitHub (public projects, not private repos);YouTube;LinkedIn;Medium",NaN,NaN,NaN,NaN,Yes,Alibaba Cloud Qwen models;Anthropic: Claude Sonnet;DeepSeek (R- Reasoning models);Gemini (Flash general purpose models);Gemini (Pro Reasoning models);openAI GPT (chatbot models),NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Overflow,NaN,14.0,NaN,10.0,4.0,7.0,3.0,5.0,6.0,11.0,1.0,Find solution to problems,"No, not at all","Rarely, almost never","Yes, I use AI tools daily",Very favorable,Somewhat trust,Very poor at handling complex tasks,Learning about a codebase;Documenting code;Debugging or fixing code;Testing code;Deployment and monitoring;Search for answers;Learning new concepts or technologies,Committing and reviewing code;Predictive analytics,Writing code,NaN,Project planning;Generating content or synthetic data;Creating or maintaining documentation,"AI solutions that are almost right, but not quite;Debugging AI-generated code is more time-consuming","No, I am not a vibe coder.","Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Vector databases for AI applications;Integration with external agents and APIs,AI agents have accelerated my learning about new technologies or codebases.;AI agents have reduced the time spent on specific development tasks.,AI agents have improved collaboration within my team.,AI agents have increased my productivity.;AI agents have helped me automate repetitive tasks.;AI agents have improved the quality of my code.;AI agents have helped me solve complex problems more effectively.,NaN,NaN,Integrating AI agents with my existing tools and workflows can be difficult.,It takes significant time and effort to learn how to use AI agents effectively.;I have concerns about the security and privacy of data when using AI agents.;My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,I am concerned about the accuracy of the information provided by AI agents.;The cost of using certain AI agent platforms is a barrier.,NaN,Redis;GitHub MCP Server;ChromaDB,"LangChain, LangGraph, Elasticsearch",Ollama;LangChain;LangGraph;Smolagents,NaN,LangSmith,NaN,ChatGPT;GitHub Copilot;Google Gemini;v0.dev,NaN,When I don’t trust AI’s answers;When I have ethical or security concerns about code;When I need help fixing complex or unfamiliar code,Understanding the fundamentals and how to solve problems.,12533.0,7.0
1365,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Other online resources (e.g. standard search, forum, online community);Books / Physical media;Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Blogs or podcasts;School (i.e., University, College, etc)","No, I learned something that was not related to AI or AI enablement for my personal curiosity and/or hobbies",NaN,8.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibility)","Yes, I endorsed a tool that was ultimately not purchased or used at my organization",Work,13.0,7.0,6.0,5.0,2.0,3.0,11.0,1.0,4.0,14.0,NaN,14.0,2.0,10.0,13.0,4.0,1.0,7.0,3.0,12.0,15.0,NaN,Software Development,6.0,5.0,8.0,11.0,10.0,13.0,1.0,7.0,14.0,9.0,2.0,3.0,4.0,15.0,12.0,NaN,No,I have neither consider or transitioned into a new career or industry,5.0,15.0,Morocco,MAD\tMoroccan dirham,120000.0,Yes,Bash/Shell (all shells);C;C#;C++;Fortran;Java;JavaScript;Lisp;Perl;Python;Ruby;TypeScript,C;C#;C++;Elixir;Erlang;Go;Java;Lisp;Rust;Scala;Swift;TypeScript;Zig,C;C#;C++;Java;Lisp;TypeScript,NaN,NaN,Yes,Cassandra;Elasticsearch;H2;MariaDB;Microsoft SQL Server;MongoDB;MySQL;Oracle;PostgreSQL;Redis;SQLite,Cassandra;Cosmos DB;Dynamodb;Elasticsearch;H2;MariaDB;Microsoft SQL Server;MongoDB;MySQL;Oracle;PostgreSQL;Redis;SQLite;Supabase;Valkey,Cassandra;Elasticsearch;H2;MariaDB;Microsoft SQL Server;MongoDB;MySQL;Oracle;PostgreSQL;Redis;SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);Ansible;Docker;Google Cloud;Gradle;Homebrew;Kubernetes;Make;Maven (build tool);Microsoft Azure;npm;Pip;Vercel;Yarn,Amazon Web Services (AWS);Datadog;Digital Ocean;Docker;Firebase;Google Cloud;Gradle;Kubernetes;Make;Maven (build tool);Microsoft Azure;npm;Podman;Prometheus;Supabase;Vercel;Vite;Webpack;Yarn,Amazon Web Services (AWS);Docker;Google Cloud;Gradle;Kubernetes;Make;Maven (build tool);Microsoft Azure;npm;Vercel;Yarn,NaN,NaN,Yes,Angular;AngularJS;ASP.NET;ASP.NET Core;Django;Express;FastAPI;Flask;jQuery;Laravel;Next.js;React;Ruby on Rails;Spring Boot,Angular;Express;FastAPI;Flask;Ruby on Rails;Spring Boot;Vue.js,Angular;Express;FastAPI;Flask;Ruby on Rails;Spring Boot,NaN,NaN,NaN,Eclipse;IntelliJ IDEA;Jupyter Notebook/JupyterLab;Sublime Text;Vim;Visual Studio;Visual Studio Code;WebStorm;Xcode,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Sublime Text;Vim;Visual Studio;Visual Studio Code;WebStorm;Xcode,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Sublime Text;Vim;Visual Studio;Visual Studio Code;WebStorm;Xcode,Emacs,NaN,c++23,c++23,c++23,NaN,NaN,Windows;MacOS;Android;Windows Subsystem for Linux (WSL);iOS;Debian;Fedora,Windows;Ubuntu;Android,Azure Devops;Confluence;GitHub;GitLab;Jira;Stack Overflow for Teams,Azure Devops;Confluence;GitHub;GitLab;Jira,Azure Devops;Confluence;GitHub;GitLab;Jira,NaN,NaN,"Stack Overflow;Stack Exchange;GitHub (public projects, not private repos);Slack (public channels, not work);Kaggle;YouTube;LinkedIn;Substack;Medium","Stack Overflow;Stack Exchange;GitHub (public projects, not private repos);YouTube;LinkedIn;Substack;Medium","Stack Overflow;Stack Exchange;GitHub (public projects, not private repos);YouTube;LinkedIn;Substack;Medium",NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,Less than once every 2 - 3 months,"Long-form articles;Coding challenges;Logic games/puzzles;Lists of recommendations (tools, frameworks, technologies, etc.);Day-in-the-life profiles/interviews with experts",4.0,NaN,3.0,2.0,5.0,8.0,7.0,6.0,9.0,15.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools monthly or infrequently",Unfavorable,Somewhat distrust,Bad at handling complex tasks,NaN,Writing code;Documenting code;Debugging or fixing code;Committing and reviewing code;Creating or maintaining documentation;Learning new concepts or technologies,Learning about a codebase;Project planning;Testing code;Deployment and monitoring;Search for answers;Generating content or synthetic data,Predictive analytics,NaN,Debugging AI-generated code is more time-consuming;I don’t use AI tools regularly,Vibe coding is NOT software engineering,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,Integrating AI agents with my existing tools and workflows can be difficult.,I am concerned about the accuracy of the information provided by AI agents.,I have concerns about the security and privacy of data when using AI agents.,It takes significant time and effort to learn how to use AI agents effectively.;The cost of using certain AI agent platforms is a barrier.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to fully understand something;When I want to learn best practices;When I want to compare different solutions;When I have ethical or security concerns about code;When I’m stuck and can’t explain the problem;When I need help fixing complex or unfamiliar code,"System Design, Problem Solving, Implementation",13192.0,8.0
2251,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (less than 10 hours per week),1.0,"Yes, I am not new to coding but am learning new coding techniques or programming language","Other online resources (e.g. standard search, forum, online community);Videos (not associated with specific online course or certification);Stack Overflow or Stack Exchange;Technical documentation (is generated for/by the tool or system);Blogs or podcasts","Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies","Technical documentation (is generated for/by the tool or system);Videos (not associated with specific online course or certification);Other online resources (e.g. standard search, forum, online community);Blogs or podcasts",6.0,"Developer, front-end","1,000 to 4,999 employees",Individual contributor,"Hybrid (some in-person, leans heavy to flexibility)","Yes, I endorsed a tool that was open-source and is currently used by more than just myself but no purchase was made",Personal Project,5.0,3.0,7.0,4.0,2.0,8.0,9.0,1.0,6.0,10.0,NaN,7.0,3.0,8.0,4.0,9.0,5.0,6.0,2.0,1.0,10.0,NaN,Software Development,5.0,1.0,2.0,11.0,8.0,4.0,3.0,7.0,14.0,12.0,6.0,10.0,9.0,15.0,13.0,NaN,No,I have transitioned into a new career and/or industry voluntarily,7.0,5.0,Morocco,MAD\tMoroccan dirham,110000.0,Yes,HTML/CSS;JavaScript;TypeScript,NaN,NaN,NaN,NaN,Yes,MongoDB;PostgreSQL;Supabase,NaN,NaN,NaN,NaN,Yes,Bun;Docker;Kubernetes;Maven (build tool);Netlify;npm;Pacman;pnpm;Supabase;Vercel;Vite;Webpack;Yarn,NaN,NaN,NaN,NaN,Yes,Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,Yes,Cursor;Visual Studio Code,Windsurf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Ubuntu,GitHub;GitLab;Jira;Linear;Notion,NaN,NaN,NaN,NaN,"Stack Overflow;Discord;GitHub (public projects, not private repos);Slack (public channels, not work);YouTube;LinkedIn",NaN,NaN,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI GPT (chatbot models),NaN,NaN,Claude,NaN,Yes,A few times per week,Between 1 and 3 years,I have never participated in Q&A on Stack Overflow,"Lists of recommendations (tools, frameworks, technologies, etc.);Chat (bot/AI)",12.0,NaN,2.0,1.0,4.0,10.0,13.0,6.0,5.0,15.0,NaN,"Yes, somewhat",Less than half of the time,"Yes, I use AI tools daily",Very favorable,Highly trust,"Good, but not great at handling complex tasks",Learning about a codebase;Project planning;Writing code;Debugging or fixing code;Creating or maintaining documentation,NaN,Committing and reviewing code;Deployment and monitoring;Generating content or synthetic data;Learning new concepts or technologies,Testing code;Predictive analytics;Search for answers,Documenting code,"AI solutions that are almost right, but not quite;I’ve become less confident in my own problem-solving","Yes, ""vibe coding"" has become part of my daily workflow because it's faster to generate code than writing it from scratch, but still, I'm not 100% AI-driven; I just use it as ""automation"" to get faster results.","No, but I plan to","Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools and workflows can be difficult.;It takes significant time and effort to learn how to use AI agents effectively.,NaN,The cost of using certain AI agent platforms is a barrier.;I have concerns about the security and privacy of data when using AI agents.,I am concerned about the accuracy of the information provided by AI agents.,My company's IT and/or InfoSec teams have strict rules that do not allow me to use AI agent tools or platforms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to learn best practices;When I have ethical or security concerns about code;I don’t think I’ll need help from people anymore,"No matter how capable AI becomes, I don't think it will eliminate developers, but a developer must have a good understanding of basic logic, analysis, and the ability to leverage AI.",12093.0,7.0

In [ ]:
filt = (df1['Country'] == 'Morocco')
df1[filt]['LanguageChoice'].value_counts()

LanguageChoice
Yes    46
Name: count, dtype: int64